package audiotrack.controller;

public enum Commands {
    SIGN_UP,
    CHANGE_LOCAL,
    SIGN_IN,
    AFTER_AUTHENTICATION,
    AFTER_REGISTRATION,
    SHOW_USERS,
    BEFORE_ADD_TRACK,
    ADD_TRACK,
    LOG_OUT,
    SHOW_TRACKS,
    DELETE_TRACK,
    UPDATE_TRACK,
    ADD_ALBUM,
    ADD_PLAYLIST,
    BEFORE_UPDATE_TRACK,
    ADD_COMMENT,
    MAKE_ORDER,
    UPDATE_USER_DISCOUNT,
    BEFORE_UPDATE_USER_DISCOUNT,
    BEFORE_ADD_COMMENT,
    SHOW_CLIENT_TRACKS,
    SHOW_COMMENTS_TRACK;
}
